//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article_Info()
        {
            this.Article_Photo = new HashSet<Article_Photo>();
            this.Article_Reference = new HashSet<Article_Reference>();
            this.Bon_CodeBarre = new HashSet<Bon_CodeBarre>();
            this.Bon_Entree_Article = new HashSet<Bon_Entree_Article>();
            this.Bon_reference = new HashSet<Bon_reference>();
            this.Bon_Retour_Article = new HashSet<Bon_Retour_Article>();
            this.Bon_Sortie_Article = new HashSet<Bon_Sortie_Article>();
            this.Emplacements = new HashSet<Emplacement>();
            this.Mouvements = new HashSet<Mouvement>();
            this.Position_Actuelle = new HashSet<Position_Actuelle>();
            this.Unite_Mesure = new HashSet<Unite_Mesure>();
            this.Vehicule_Article = new HashSet<Vehicule_Article>();
        }
    
        public int art_ID { get; set; }
        public string art_Designation { get; set; }
        public string art_Abreviation { get; set; }
        public string art_Description { get; set; }
        public Nullable<int> svc_ID { get; set; }
        public Nullable<int> fam_ID { get; set; }
        public Nullable<bool> art_Status { get; set; }
    
        public virtual Famille Famille { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Photo> Article_Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Reference> Article_Reference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_CodeBarre> Bon_CodeBarre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Entree_Article> Bon_Entree_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_reference> Bon_reference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Retour_Article> Bon_Retour_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Sortie_Article> Bon_Sortie_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emplacement> Emplacements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mouvement> Mouvements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position_Actuelle> Position_Actuelle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unite_Mesure> Unite_Mesure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicule_Article> Vehicule_Article { get; set; }
    }
}
