//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Reference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article_Reference()
        {
            this.Article_CodeBarre = new HashSet<Article_CodeBarre>();
            this.Bon_CodeBarre = new HashSet<Bon_CodeBarre>();
            this.Bon_reference = new HashSet<Bon_reference>();
            this.Emplacements = new HashSet<Emplacement>();
            this.Mouvements = new HashSet<Mouvement>();
            this.Position_Actuelle = new HashSet<Position_Actuelle>();
            this.Vehicule_Article = new HashSet<Vehicule_Article>();
        }
    
        public int ref_ID { get; set; }
        public Nullable<int> art_ID { get; set; }
        public string ref_reference { get; set; }
        public Nullable<bool> ref_est_Gravee { get; set; }
        public string ref_Description { get; set; }
        public Nullable<bool> ref_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_CodeBarre> Article_CodeBarre { get; set; }
        public virtual Article_Info Article_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_CodeBarre> Bon_CodeBarre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_reference> Bon_reference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emplacement> Emplacements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mouvement> Mouvements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position_Actuelle> Position_Actuelle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicule_Article> Vehicule_Article { get; set; }
    }
}
