//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_CodeBarre
    {
        public int cb_ID { get; set; }
        public Nullable<System.DateTime> cb_Date_Ajout { get; set; }
        public Nullable<System.DateTime> cb_Date_Gravage { get; set; }
        public Nullable<bool> cb_Status_Gravage { get; set; }
        public string cb_N_serie { get; set; }
        public Nullable<int> ref_ID { get; set; }
        public Nullable<int> act_ID { get; set; }
        public string cb_Description { get; set; }
        public Nullable<bool> cb_Status { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Article_Reference Article_Reference { get; set; }
    }
}
