//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_CodeBarre
    {
        public int bc_ID { get; set; }
        public Nullable<System.DateTime> bc_Date { get; set; }
        public string bc_Type { get; set; }
        public string bc_N_Serie { get; set; }
        public Nullable<int> bc_Numero { get; set; }
        public Nullable<int> bc_Annee { get; set; }
        public Nullable<int> ref_ID { get; set; }
        public Nullable<int> art_ID { get; set; }
        public Nullable<int> bon_ID { get; set; }
        public Nullable<int> vl_ID { get; set; }
    
        public virtual Article_Info Article_Info { get; set; }
        public virtual Article_Reference Article_Reference { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
