//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enregistrement
    {
        public int eng_ID { get; set; }
        public Nullable<System.DateTime> eng_Date { get; set; }
        public Nullable<System.TimeSpan> eng_Time { get; set; }
        public Nullable<int> util_ID { get; set; }
        public string eng_pc_Name { get; set; }
        public string eng_Operation { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
