//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magasin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magasin()
        {
            this.Emplacements = new HashSet<Emplacement>();
        }
    
        public int mags_ID { get; set; }
        public string mags_Magasin { get; set; }
        public Nullable<int> vil_ID { get; set; }
        public string mags_Description { get; set; }
        public Nullable<bool> mags_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emplacement> Emplacements { get; set; }
        public virtual Ville Ville { get; set; }
    }
}
