//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouvement
    {
        public int mvt_ID { get; set; }
        public Nullable<System.DateTime> mvt_Date { get; set; }
        public string mvt_Doc_Refference { get; set; }
        public Nullable<int> ref_ID { get; set; }
        public Nullable<int> vl_ID { get; set; }
        public Nullable<int> art_ID { get; set; }
        public Nullable<decimal> mvt_Qte { get; set; }
        public Nullable<decimal> unit_M_Coefficient { get; set; }
        public Nullable<int> unit_M_ID { get; set; }
        public Nullable<decimal> mvt_Qte_Calc { get; set; }
        public string bon_Type { get; set; }
        public Nullable<int> bon_ID { get; set; }
        public Nullable<int> bs_A_ID { get; set; }
        public Nullable<int> be_A_ID { get; set; }
        public Nullable<int> bt_A_ID { get; set; }
    
        public virtual Article_Info Article_Info { get; set; }
        public virtual Article_Reference Article_Reference { get; set; }
        public virtual Bon_Entree_Article Bon_Entree_Article { get; set; }
        public virtual Bon_Retour_Article Bon_Retour_Article { get; set; }
        public virtual Bon_Sortie_Article Bon_Sortie_Article { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
