//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pers_GSM
    {
        public int gsm_ID { get; set; }
        public string gsm_GSM { get; set; }
        public Nullable<int> pers_ID { get; set; }
        public Nullable<bool> gsm_Status { get; set; }
    
        public virtual pers_Affecte pers_Affecte { get; set; }
    }
}
