//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public int scrn_ID { get; set; }
        public string scrn_Nom { get; set; }
        public int list_ID { get; set; }
    
        public virtual List List { get; set; }
    }
}
