//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    
    public partial class Select_Unite_Mesure_By_Art_isDefault_Result1
    {
        public int unit_M_ID { get; set; }
        public Nullable<int> art_ID { get; set; }
        public string unit_M_Nom { get; set; }
        public string unit_M_Abreviation { get; set; }
        public Nullable<decimal> unit_M_Coefficient { get; set; }
        public Nullable<bool> unit_M_isDefault { get; set; }
        public Nullable<decimal> unit_M_Min { get; set; }
        public Nullable<decimal> unit_M_Max { get; set; }
        public Nullable<bool> unit_M_Status { get; set; }
    }
}
