//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unite_Mesure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unite_Mesure()
        {
            this.Bon_Entree_Article = new HashSet<Bon_Entree_Article>();
            this.Bon_Retour_Article = new HashSet<Bon_Retour_Article>();
            this.Bon_Sortie_Article = new HashSet<Bon_Sortie_Article>();
        }
    
        public int unit_M_ID { get; set; }
        public Nullable<int> art_ID { get; set; }
        public string unit_M_Nom { get; set; }
        public string unit_M_Abreviation { get; set; }
        public Nullable<decimal> unit_M_Coefficient { get; set; }
        public Nullable<bool> unit_M_isDefault { get; set; }
        public Nullable<decimal> unit_M_Min { get; set; }
        public Nullable<decimal> unit_M_Max { get; set; }
        public Nullable<bool> unit_M_Status { get; set; }
    
        public virtual Article_Info Article_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Entree_Article> Bon_Entree_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Retour_Article> Bon_Retour_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Sortie_Article> Bon_Sortie_Article { get; set; }
    }
}
