//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Emplacement
    {
        public int eplc_ID { get; set; }
        public Nullable<System.DateTime> eplc_Date { get; set; }
        public string mags_Magasin { get; set; }
        public string art_Designation { get; set; }
        public string ref_reference { get; set; }
        public string rayo_Nom { get; set; }
        public string arm_Nom { get; set; }
        public string eplc_Description { get; set; }
    }
}
