//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Priv
    {
        public Nullable<int> util_ID { get; set; }
        public Nullable<int> scrn_ID { get; set; }
        public string scrn_Nom { get; set; }
        public int list_ID { get; set; }
        public Nullable<bool> priv_Afficher { get; set; }
        public Nullable<bool> priv_Ajouter { get; set; }
        public Nullable<bool> priv_Modifier { get; set; }
        public Nullable<bool> priv_Supprimer { get; set; }
    }
}
