//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Utilisateur
    {
        public int util_ID { get; set; }
        public int pers_ID { get; set; }
        public string pers_Prenom { get; set; }
        public string pers_Nom { get; set; }
        public string pers_Mle_FA { get; set; }
        public string grd_Grade { get; set; }
        public string util_Identifiant { get; set; }
        public string util_MotPasse { get; set; }
        public Nullable<int> svc_ID { get; set; }
        public Nullable<int> prof_ID { get; set; }
    }
}
