//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public string bc_N_Serie { get; set; }
        public int ref_ID { get; set; }
        public string ref_reference { get; set; }
        public Nullable<int> bon_ID { get; set; }
        public int bs_ID { get; set; }
    }
}
