//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int mvt_ID { get; set; }
        public string vl_Marque { get; set; }
        public string art_Designation { get; set; }
        public string ref_reference { get; set; }
        public Nullable<decimal> mvt_Qte { get; set; }
        public string bon_Type { get; set; }
        public Nullable<int> be_A_ID { get; set; }
        public Nullable<int> bt_A_ID { get; set; }
        public Nullable<int> bs_A_ID { get; set; }
        public int ref_ID { get; set; }
        public int vl_ID { get; set; }
        public int art_ID { get; set; }
        public Nullable<decimal> unit_M_Coefficient { get; set; }
        public Nullable<decimal> mvt_Qte_Calc { get; set; }
        public int unit_M_ID { get; set; }
        public string unit_M_Nom { get; set; }
        public string unit_M_Abreviation { get; set; }
    }
}
