//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwArticle_Info
    {
        public int art_ID { get; set; }
        public string art_Designation { get; set; }
        public string art_Abreviation { get; set; }
        public string art_Description { get; set; }
        public Nullable<int> svc_ID { get; set; }
        public string svc_Nom { get; set; }
        public string fam_Nom { get; set; }
        public Nullable<bool> art_Status { get; set; }
        public Nullable<int> fam_ID { get; set; }
    }
}
