//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCodeBarre
    {
        public int bc_ID { get; set; }
        public Nullable<System.DateTime> bc_Date { get; set; }
        public string bc_Type { get; set; }
        public Nullable<int> bon_ID { get; set; }
        public string bc_N_Serie { get; set; }
        public Nullable<int> bc_Numero { get; set; }
        public Nullable<int> bc_Annee { get; set; }
        public string ref_reference { get; set; }
        public string art_Designation { get; set; }
        public string vl_Marque { get; set; }
    }
}
