//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMagasin
    {
        public int mags_ID { get; set; }
        public string mags_Magasin { get; set; }
        public string vil_Nom { get; set; }
        public string mags_Description { get; set; }
        public Nullable<bool> mags_Status { get; set; }
    }
}
